# Generated by Django 5.0.7 on 2024-07-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('cuisine', models.CharField(blank=True, max_length=100, null=True)),
                ('vegetarian', models.BooleanField(default=False)),
            ],
        ),
    ]
